version: '3.8'

services:
  ultra-god-mode-ai:
    build: .
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=ultra_god_mode_transcendent_infinity
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - PORT=5000
      - FLASK_ENV=production
    volumes:
      - ./models:/app/models
      - ./logs:/app/logs
      - ./data:/app/data
      - ./uploads:/app/uploads
    restart: unless-stopped
    
  # Optional: Redis for caching (uncomment if needed)
  # redis:
  #   image: redis:alpine
  #   restart: unless-stopped
